WIP: B-C: adjust for UV as first sv_u member
but C89 compilers cannot take pointers to int members at compile-time.
so we cannot use that change.

 error: initializer element is not a compile-time constant
        { &xpv_list[3], 1, 0x4403, {(UV)pv3} }, /* sv_list[18]  */